# Numpy
## 什麼是Numpy?
![](https://i.imgur.com/X0pj3xu.png)

## 複習 List

In [3]:
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
print(list_1, list_2)

[1, 2, 3, 4] [5, 6, 7, 8]


## 建立Numpy 陣列

In [6]:
import numpy as np
np_1 = np.array(list_1)
print(np_1)

[1 2 3 4]


## 觀察陣資料型態

In [8]:
np_1.dtype

dtype('int32')

## 轉換資料型態

In [10]:
tmp = np_1.astype(np.float64)
tmp.dtype

dtype('float64')

## 陣列運算
lst1 = [1, 2, 3, 4]<br>lst2 = [5, 6, 7, 8]

In [12]:
np_1*2

array([2, 4, 6, 8])

In [14]:
np_2 = np.array(list_2)
np_1 + np_2

array([ 6,  8, 10, 12])

In [17]:
np_1 * np_2

array([ 5, 12, 21, 32])

## 陣列中取值和定義新的數值
lst1 = [1, 2, 3, 4]<br>lst2 = [5, 6, 7, 8]

In [15]:
np_1[1]

2

In [16]:
np_1[1:3]

array([2, 3])

In [18]:
np_1[1:]

array([2, 3, 4])

In [19]:
np_1[-1]

4

In [23]:
np_1[0] = 18
np_1
np_1[0] = 1

## 將一維陣列改為二維陣列
矩陣

In [25]:
np_1 = np_1.reshape((2,2))
np_1

array([[1, 2],
       [3, 4]])

In [26]:
np_2 = np_2.reshape((2,2))
np_2

array([[5, 6],
       [7, 8]])

## 矩陣相乘
![](https://i.imgur.com/DLAVQD1.png)

In [28]:
np_1.dot(np_2)

array([[19, 22],
       [43, 50]])